# Generated by Django 3.1 on 2020-09-15 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_feed',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='vid_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
