# Generated by Django 3.1 on 2020-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0002_auto_20200915_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_feed',
            name='channel_name',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='last_30_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='length',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='yesterday',
            field=models.IntegerField(null=True),
        ),
    ]
