# Generated by Django 3.1 on 2020-09-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0003_auto_20200915_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module_feed',
            old_name='date',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='module_feed',
            old_name='vid_file',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='module_feed',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='module_feed',
            name='module_name',
        ),
    ]
