# Generated by Django 3.1 on 2020-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0004_auto_20200915_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='channel_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
