# Generated by Django 3.1 on 2020-09-18 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0005_auto_20200915_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module_feed',
            old_name='last_30_days',
            new_name='ad_dislikes',
        ),
        migrations.RenameField(
            model_name='module_feed',
            old_name='yesterday',
            new_name='ad_likes',
        ),
        migrations.RemoveField(
            model_name='module_feed',
            name='video_file',
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_channel_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_cta_link',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_genre',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_links',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_unlisted',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='ad_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='orgv_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='subscribers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='module_feed',
            name='total_videos',
            field=models.IntegerField(null=True),
        ),
    ]
