# Generated by Django 3.1 on 2020-09-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0006_auto_20200918_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='creation_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='upload_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
