# Generated by Django 3.1 on 2020-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0008_auto_20200918_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_description',
            field=models.TextField(null=True),
        ),
    ]
