# Generated by Django 3.1 on 2020-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0012_auto_20200918_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_cta_link',
            field=models.URLField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_genre',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_links',
            field=models.URLField(max_length=510, null=True),
        ),
    ]
