# Generated by Django 3.1 on 2020-09-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0013_auto_20200918_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_channel_link',
            field=models.URLField(max_length=510, null=True),
        ),
    ]
