# Generated by Django 3.1 on 2020-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0015_auto_20200918_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_channel_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_cta_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_links',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_unlisted',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='channel_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='creation_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='length',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='orgv_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='upload_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
