# Generated by Django 3.1 on 2020-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0017_auto_20200918_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_cta_link',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
