# Generated by Django 3.1 on 2020-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0019_auto_20200918_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_channel_link',
            field=models.URLField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_url',
            field=models.URLField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='channel_name',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='creation_date',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='orgv_url',
            field=models.URLField(max_length=510, null=True),
        ),
    ]
