# Generated by Django 3.1 on 2020-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0020_auto_20200918_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_channel_link',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_cta_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_links',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='ad_url',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='module_feed',
            name='orgv_url',
            field=models.CharField(max_length=510, null=True),
        ),
    ]
