# Generated by Django 3.1 on 2020-09-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0026_auto_20200918_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_feed',
            name='ad_cta_link',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
